# Input dimensions
img_height : 32
img_width : 32
num_classes : 43

# Training
batch_size : 64
epochs : 20
learning_rate : 0.001
loss_function : "categorical_crossentropy"
metrics : "accuracy"

# Path to train data
path_to_data :  '..\data\'
path_to_train_csv : '..\data\Train.csv'
path_to_test_csv : '..\data\Test.csv'
